### ISSUE TITLE
TypeError: Non-hexadecimal digit found

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/ikeforce#1]
Getting the following error when running ikeforce:
Encrypted payload received.
Encrypted Payload: 768b4af3fd440dfe3d584f392af38db99907a97b60c1383b49c8493e95889882d1f8035fea1694e4f8826b5d8a230b68aeffe1b23dddc6197355ab8b11200cef491eab4e28919f46cedaeda02f3eb59758bb7fb4b0d36da4f914b0178b0af3a5
Traceback (most recent call last):
  File "./ikeforce.py", line 708, in <module>
    respDict,listVIDs = ikeHandling.main(packets[-1],encType,hashType,encKey,initIV,curIV)
  File "/opt/ikeforce/ikehandler.py", line 618, in main
    ikeDecrypt = ikeCrypto.ikeCipher(encKey, initIV.decode('hex'), encType)
  File "/usr/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
    output = binascii.a2b_hex(input)
TypeError: Non-hexadecimal digit found

**Comment by f0cker** [comment]
This looks like a decryption issue, but it's hard to tell without further detail. Can you paste the full command masking anything sensitive and including debug output (-d)? Also any device version information you have would be useful.

I'm pretty sure handling this error is already fixed in the latest version, but I haven't had time to finish off the development and release it.
